/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const RoadmapMilestone = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Opt(IDL.Text),
  'completed' : IDL.Bool,
  'year' : IDL.Text,
  'description' : IDL.Text,
});
export const TokenInfo = IDL.Record({
  'ticker' : IDL.Text,
  'socialLinks' : IDL.Vec(IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text })),
  'name' : IDL.Text,
  'launchPlatform' : IDL.Text,
  'description' : IDL.Text,
  'totalSupply' : IDL.Text,
  'slogan' : IDL.Text,
  'distribution' : IDL.Text,
});

export const idlService = IDL.Service({
  'adminUpdateMilestone' : IDL.Func([IDL.Text, IDL.Bool], [Result], []),
  'getRoadmap' : IDL.Func([], [IDL.Vec(RoadmapMilestone)], ['query']),
  'getTokenInfo' : IDL.Func([], [TokenInfo], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const RoadmapMilestone = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Opt(IDL.Text),
    'completed' : IDL.Bool,
    'year' : IDL.Text,
    'description' : IDL.Text,
  });
  const TokenInfo = IDL.Record({
    'ticker' : IDL.Text,
    'socialLinks' : IDL.Vec(
      IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text })
    ),
    'name' : IDL.Text,
    'launchPlatform' : IDL.Text,
    'description' : IDL.Text,
    'totalSupply' : IDL.Text,
    'slogan' : IDL.Text,
    'distribution' : IDL.Text,
  });
  
  return IDL.Service({
    'adminUpdateMilestone' : IDL.Func([IDL.Text, IDL.Bool], [Result], []),
    'getRoadmap' : IDL.Func([], [IDL.Vec(RoadmapMilestone)], ['query']),
    'getTokenInfo' : IDL.Func([], [TokenInfo], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };