/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Result = { 'ok' : null } |
  { 'err' : string };
export interface RoadmapMilestone {
  'id' : string,
  'title' : string,
  'date' : [] | [string],
  'completed' : boolean,
  'year' : string,
  'description' : string,
}
export interface TokenInfo {
  'ticker' : string,
  'socialLinks' : Array<{ 'url' : string, 'name' : string }>,
  'name' : string,
  'launchPlatform' : string,
  'description' : string,
  'totalSupply' : string,
  'slogan' : string,
  'distribution' : string,
}
export interface _SERVICE {
  'adminUpdateMilestone' : ActorMethod<[string, boolean], Result>,
  'getRoadmap' : ActorMethod<[], Array<RoadmapMilestone>>,
  'getTokenInfo' : ActorMethod<[], TokenInfo>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];