/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BinancePost = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'snippet' : IDL.Text,
});
export const Result_5 = IDL.Variant({ 'ok' : BinancePost, 'err' : IDL.Text });
export const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const FAQ = IDL.Record({
  'id' : IDL.Text,
  'question' : IDL.Text,
  'order' : IDL.Nat,
  'answer' : IDL.Text,
});
export const Result_4 = IDL.Variant({ 'ok' : FAQ, 'err' : IDL.Text });
export const JournalEntry = IDL.Record({
  'id' : IDL.Text,
  'pnl' : IDL.Opt(IDL.Float64),
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'entryPrice' : IDL.Float64,
  'signal' : IDL.Text,
  'exitPrice' : IDL.Opt(IDL.Float64),
});
export const MarketType = IDL.Variant({
  'Stock' : IDL.Null,
  'Forex' : IDL.Null,
  'Crypto' : IDL.Null,
});
export const Direction = IDL.Variant({ 'Buy' : IDL.Null, 'Sell' : IDL.Null });
export const Confidence = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const Timeframe = IDL.Variant({
  'Scalp' : IDL.Null,
  'Swing' : IDL.Null,
  'LongTerm' : IDL.Null,
});
export const ResultStatus = IDL.Variant({
  'Win' : IDL.Null,
  'Loss' : IDL.Null,
  'Active' : IDL.Null,
  'Expired' : IDL.Null,
});
export const Signal = IDL.Record({
  'id' : IDL.Text,
  'result' : ResultStatus,
  'marketType' : MarketType,
  'direction' : Direction,
  'asset' : IDL.Text,
  'timeframe' : Timeframe,
  'publishAt' : IDL.Opt(IDL.Int),
  'targetPrice' : IDL.Text,
  'isDraft' : IDL.Bool,
  'datePosted' : IDL.Text,
  'stopLoss' : IDL.Text,
  'sourceLabel' : IDL.Text,
  'notes' : IDL.Text,
  'entryPrice' : IDL.Text,
  'expiry' : IDL.Opt(IDL.Int),
  'confidence' : Confidence,
});
export const Result_3 = IDL.Variant({ 'ok' : Signal, 'err' : IDL.Text });
export const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const AbTest = IDL.Record({
  'id' : IDL.Text,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'variantA' : IDL.Text,
  'variantB' : IDL.Text,
  'impressionsA' : IDL.Nat,
  'impressionsB' : IDL.Nat,
});
export const Result_19 = IDL.Variant({
  'ok' : IDL.Vec(AbTest),
  'err' : IDL.Text,
});
export const PushNotification = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'expiresAt' : IDL.Opt(IDL.Int),
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const ActivityEntry = IDL.Record({
  'dayOfWeek' : IDL.Nat,
  'hour' : IDL.Nat,
  'count' : IDL.Nat,
});
export const Result_18 = IDL.Variant({
  'ok' : IDL.Vec(ActivityEntry),
  'err' : IDL.Text,
});
export const MarketCount = IDL.Record({
  'count' : IDL.Nat,
  'market' : IDL.Text,
});
export const DateCount = IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat });
export const Analytics = IDL.Record({
  'signalsByMarket' : IDL.Vec(MarketCount),
  'notifyMeByDate' : IDL.Vec(DateCount),
  'totalNotifyMe' : IDL.Nat,
});
export const Result_17 = IDL.Variant({ 'ok' : Analytics, 'err' : IDL.Text });
export const Announcement = IDL.Record({
  'id' : IDL.Text,
  'link' : IDL.Opt(IDL.Text),
  'publishAt' : IDL.Opt(IDL.Int),
  'text' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const AuditEntry = IDL.Record({
  'id' : IDL.Text,
  'action' : IDL.Text,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
});
export const Result_16 = IDL.Variant({
  'ok' : IDL.Vec(AuditEntry),
  'err' : IDL.Text,
});
export const Result_15 = IDL.Variant({
  'ok' : IDL.Vec(IDL.Text),
  'err' : IDL.Text,
});
export const BurnScheduleEntry = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'date' : IDL.Text,
  'txHash' : IDL.Opt(IDL.Text),
  'amount' : IDL.Text,
  'reason' : IDL.Text,
});
export const BurnTracker = IDL.Record({
  'lastUpdated' : IDL.Int,
  'totalBurned' : IDL.Nat,
});
export const CommunityCounter = IDL.Record({
  'lastUpdated' : IDL.Int,
  'binanceCount' : IDL.Nat,
  'twitterCount' : IDL.Nat,
});
export const HolderBenefit = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'icon' : IDL.Text,
  'description' : IDL.Text,
});
export const Result_14 = IDL.Variant({
  'ok' : IDL.Vec(JournalEntry),
  'err' : IDL.Text,
});
export const MaintenanceMode = IDL.Record({
  'enabled' : IDL.Bool,
  'updatedAt' : IDL.Int,
  'message' : IDL.Text,
});
export const MarketMoodBanner = IDL.Record({
  'active' : IDL.Bool,
  'mood' : IDL.Text,
  'updatedAt' : IDL.Int,
  'message' : IDL.Text,
});
export const PriceData = IDL.Record({
  'trend' : IDL.Text,
  'asset' : IDL.Text,
  'updatedAt' : IDL.Int,
  'priceChange24h' : IDL.Float64,
  'price' : IDL.Float64,
});
export const SentimentLevel = IDL.Variant({
  'Bearish' : IDL.Null,
  'Neutral' : IDL.Null,
  'Bullish' : IDL.Null,
});
export const AssetSentiment = IDL.Record({
  'trend' : IDL.Text,
  'asset' : IDL.Text,
  'note' : IDL.Text,
  'lastPriceUpdate' : IDL.Int,
  'level' : SentimentLevel,
  'updatedAt' : IDL.Int,
  'priceChange24h' : IDL.Float64,
  'market' : IDL.Text,
  'price' : IDL.Float64,
});
export const MarketSentiment = IDL.Record({
  'assets' : IDL.Vec(AssetSentiment),
  'updatedAt' : IDL.Int,
  'overall' : SentimentLevel,
});
export const CommunityMilestone = IDL.Record({
  'id' : IDL.Text,
  'reached' : IDL.Bool,
  'celebrateUntil' : IDL.Opt(IDL.Int),
  'title' : IDL.Text,
  'description' : IDL.Text,
  'reachedAt' : IDL.Opt(IDL.Int),
});
export const NotifyMe = IDL.Record({
  'id' : IDL.Text,
  'contact' : IDL.Text,
  'dateSubmitted' : IDL.Text,
  'name' : IDL.Opt(IDL.Text),
});
export const Result_13 = IDL.Variant({
  'ok' : IDL.Vec(NotifyMe),
  'err' : IDL.Text,
});
export const DemonZenoQuote = IDL.Record({
  'id' : IDL.Text,
  'active' : IDL.Bool,
  'quote' : IDL.Text,
  'author' : IDL.Text,
});
export const RoadmapMilestone = IDL.Record({
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'year' : IDL.Text,
  'description' : IDL.Text,
});
export const Result_9 = IDL.Variant({
  'ok' : IDL.Vec(Signal),
  'err' : IDL.Text,
});
export const ResponseRating = IDL.Record({
  'messageId' : IDL.Text,
  'timestamp' : IDL.Int,
  'rating' : IDL.Int,
});
export const Result_12 = IDL.Variant({
  'ok' : IDL.Vec(ResponseRating),
  'err' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'provider' : IDL.Opt(IDL.Text),
  'role' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const SignalOfWeekFull = IDL.Record({
  'featuredAt' : IDL.Int,
  'comment' : IDL.Text,
  'signal' : Signal,
  'weekOf' : IDL.Text,
});
export const AssetStats = IDL.Record({
  'asset' : IDL.Text,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
});
export const DayStats = IDL.Record({
  'day' : IDL.Text,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
});
export const SignalPerformanceStats = IDL.Record({
  'topAssets' : IDL.Vec(AssetStats),
  'pending' : IDL.Nat,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'weeklyTrend' : IDL.Vec(DayStats),
  'winRate' : IDL.Float64,
  'totalSignals' : IDL.Nat,
});
export const Result_11 = IDL.Variant({
  'ok' : SignalPerformanceStats,
  'err' : IDL.Text,
});
export const Stats = IDL.Record({
  'active' : IDL.Nat,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'assetsCovered' : IDL.Nat,
  'winRate' : IDL.Float64,
  'totalSignals' : IDL.Nat,
});
export const StatsConfig = IDL.Record({
  'useManual' : IDL.Bool,
  'manualStats' : IDL.Opt(Stats),
});
export const Result_10 = IDL.Variant({ 'ok' : StatsConfig, 'err' : IDL.Text });
export const Testimonial = IDL.Record({
  'id' : IDL.Text,
  'active' : IDL.Bool,
  'content' : IDL.Text,
  'asset' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'winAmount' : IDL.Opt(IDL.Text),
});
export const WhitepaperSection = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const WhitepaperContent = IDL.Record({
  'title' : IDL.Text,
  'updatedAt' : IDL.Int,
  'sections' : IDL.Vec(WhitepaperSection),
});
export const SignalInput = IDL.Record({
  'marketType' : MarketType,
  'direction' : Direction,
  'asset' : IDL.Text,
  'timeframe' : Timeframe,
  'publishAt' : IDL.Opt(IDL.Int),
  'targetPrice' : IDL.Text,
  'isDraft' : IDL.Bool,
  'stopLoss' : IDL.Text,
  'sourceLabel' : IDL.Text,
  'notes' : IDL.Text,
  'entryPrice' : IDL.Text,
  'expiry' : IDL.Opt(IDL.Int),
  'confidence' : Confidence,
});
export const AuditSnapshot = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'dataHash' : IDL.Text,
  'snapshotLabel' : IDL.Text,
});
export const Result_8 = IDL.Variant({
  'ok' : IDL.Vec(AuditSnapshot),
  'err' : IDL.Text,
});
export const Result_7 = IDL.Variant({ 'ok' : Announcement, 'err' : IDL.Text });
export const Result_6 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
export const Result_1 = IDL.Variant({
  'ok' : IDL.Tuple(IDL.Text, IDL.Text),
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBinancePost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result_5],
      [],
    ),
  'addBurnEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'addFaq' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_4], []),
  'addJournalEntry' : IDL.Func([JournalEntry, IDL.Text], [Result], []),
  'addMilestone' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
  'addQuote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
  'addSignal' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        MarketType,
        Direction,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Confidence,
        IDL.Text,
        IDL.Opt(IDL.Int),
        Timeframe,
        IDL.Bool,
        IDL.Opt(IDL.Int),
      ],
      [Result_3],
      [],
    ),
  'addTestimonial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
      [Result],
      [],
    ),
  'askFaq' : IDL.Func([IDL.Text], [IDL.Text], []),
  'backtestSignal' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'banEmail' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
  'checkAdminUnlockPhrase' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'clearJournal' : IDL.Func([IDL.Text], [Result_2], []),
  'createAbTest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'createAuditSnapshot' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'createPushNotification' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'deleteBinancePost' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
  'deleteFaq' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
  'deleteQuote' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
  'deleteSignal' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
  'deleteTestimonial' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
  'dismissPushNotification' : IDL.Func([IDL.Text], [], []),
  'generateDailyBriefing' : IDL.Func([IDL.Text], [Result], []),
  'getAbTests' : IDL.Func([IDL.Text], [Result_19], []),
  'getAbVariant' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getActivePushNotifications' : IDL.Func(
      [],
      [IDL.Vec(PushNotification)],
      ['query'],
    ),
  'getAdminActivityHeatmap' : IDL.Func([IDL.Text], [Result_18], []),
  'getAdminConfig' : IDL.Func([IDL.Text], [Result], []),
  'getAiLanguage' : IDL.Func([IDL.Text], [Result], ['query']),
  'getAiProviderStatus' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
      ['query'],
    ),
  'getAnalytics' : IDL.Func([IDL.Text], [Result_17], []),
  'getAnalyticsCsv' : IDL.Func([IDL.Text], [Result], []),
  'getAnnouncement' : IDL.Func([], [IDL.Opt(Announcement)], ['query']),
  'getAuditLog' : IDL.Func([IDL.Text], [Result_16], []),
  'getBannedEmails' : IDL.Func([IDL.Text], [Result_15], []),
  'getBinanceFeed' : IDL.Func([], [IDL.Vec(BinancePost)], ['query']),
  'getBurnSchedule' : IDL.Func([], [IDL.Vec(BurnScheduleEntry)], ['query']),
  'getBurnTracker' : IDL.Func([], [BurnTracker], ['query']),
  'getCommunityCounter' : IDL.Func([], [CommunityCounter], ['query']),
  'getDailyBriefing' : IDL.Func([], [IDL.Text], ['query']),
  'getFaqs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
  'getHolderBenefits' : IDL.Func([], [IDL.Vec(HolderBenefit)], ['query']),
  'getJournalEntries' : IDL.Func([IDL.Text], [Result_14], ['query']),
  'getMaintenanceMode' : IDL.Func([], [MaintenanceMode], ['query']),
  'getMarketMoodBanner' : IDL.Func([], [IDL.Opt(MarketMoodBanner)], ['query']),
  'getMarketPrices' : IDL.Func([], [IDL.Vec(PriceData)], ['query']),
  'getMarketSentiment' : IDL.Func([], [MarketSentiment], ['query']),
  'getMilestones' : IDL.Func([], [IDL.Vec(CommunityMilestone)], ['query']),
  'getNotifyMeList' : IDL.Func([IDL.Text], [Result_13], []),
  'getPublicBurnSchedule' : IDL.Func(
      [],
      [IDL.Vec(BurnScheduleEntry)],
      ['query'],
    ),
  'getQuotes' : IDL.Func([], [IDL.Vec(DemonZenoQuote)], ['query']),
  'getRoadmap' : IDL.Func([], [IDL.Vec(RoadmapMilestone)], ['query']),
  'getScheduledSignals' : IDL.Func([IDL.Text], [Result_9], []),
  'getSessionRatings' : IDL.Func([IDL.Text], [Result_12], ['query']),
  'getSessionRecap' : IDL.Func([IDL.Vec(ChatMessage), IDL.Text], [Result], []),
  'getSignalArchive' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
  'getSignalOfTheDay' : IDL.Func([], [IDL.Opt(Signal)], ['query']),
  'getSignalOfWeek' : IDL.Func([], [IDL.Opt(SignalOfWeekFull)], ['query']),
  'getSignalPerformanceStats' : IDL.Func([IDL.Text], [Result_11], []),
  'getSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getStatsConfig' : IDL.Func([IDL.Text], [Result_10], []),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getWhitepaper' : IDL.Func([], [WhitepaperContent], ['query']),
  'importSignals' : IDL.Func([IDL.Text, IDL.Vec(SignalInput)], [Result_9], []),
  'initFaqs' : IDL.Func([], [], []),
  'invalidateAiSession' : IDL.Func([IDL.Text], [], []),
  'invalidateSession' : IDL.Func([IDL.Text], [], []),
  'listAuditSnapshots' : IDL.Func([IDL.Text], [Result_8], []),
  'markMilestoneReached' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [Result_2],
      [],
    ),
  'publishScheduledSignals' : IDL.Func([], [IDL.Nat], []),
  'rateAiResponse' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [Result_2], []),
  'recordAbImpression' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'recordAdminActivity' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
  'refreshMarketPrices' : IDL.Func([], [IDL.Vec(PriceData)], []),
  'reorderFaqs' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [Result_2], []),
  'scheduleSignal' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [Result_2], []),
  'sendAiMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ChatMessage)],
      [Result],
      [],
    ),
  'setAiApiKey' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_2], []),
  'setAiLanguage' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
  'setAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Int)],
      [Result_7],
      [],
    ),
  'setBurnTracker' : IDL.Func([IDL.Text, BurnTracker], [Result_2], []),
  'setCommunityCounter' : IDL.Func(
      [IDL.Text, CommunityCounter],
      [Result_2],
      [],
    ),
  'setMaintenanceMode' : IDL.Func(
      [IDL.Bool, IDL.Text, IDL.Text],
      [Result_2],
      [],
    ),
  'setMarketMoodBanner' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Result_2],
      [],
    ),
  'setRoadmapMilestone' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [Result_2],
      [],
    ),
  'setSignalOfTheDay' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [Result_2], []),
  'setSignalOfWeek' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_2], []),
  'setSignalOfWeekWithDate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result_2],
      [],
    ),
  'setStatsConfig' : IDL.Func([IDL.Text, StatsConfig], [Result_2], []),
  'submitNotifyMe' : IDL.Func([IDL.Opt(IDL.Text), IDL.Text], [Result_2], []),
  'toggleAnnouncement' : IDL.Func([IDL.Text], [Result_6], []),
  'unbanEmail' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
  'updateBinancePost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result_5],
      [],
    ),
  'updateBurnEntryStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [Result_2],
      [],
    ),
  'updateFaq' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result_4],
      [],
    ),
  'updateMarketSentiment' : IDL.Func(
      [IDL.Text, MarketSentiment],
      [Result_2],
      [],
    ),
  'updateSignal' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        MarketType,
        Direction,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Confidence,
        IDL.Text,
        IDL.Opt(IDL.Int),
        Timeframe,
        IDL.Bool,
        IDL.Opt(IDL.Int),
      ],
      [Result_3],
      [],
    ),
  'updateSignalResult' : IDL.Func(
      [IDL.Text, IDL.Text, ResultStatus],
      [Result_3],
      [],
    ),
  'updateSignalSchedule' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, IDL.Opt(IDL.Int)],
      [Result_3],
      [],
    ),
  'updateWhitepaper' : IDL.Func([WhitepaperContent, IDL.Text], [Result_2], []),
  'validateAdminRole' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'validateAiPasscode' : IDL.Func([IDL.Text], [Result_1], []),
  'validateAiSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'validateInsaneSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'validatePasscode' : IDL.Func([IDL.Text], [Result], []),
  'validateSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BinancePost = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'snippet' : IDL.Text,
  });
  const Result_5 = IDL.Variant({ 'ok' : BinancePost, 'err' : IDL.Text });
  const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const FAQ = IDL.Record({
    'id' : IDL.Text,
    'question' : IDL.Text,
    'order' : IDL.Nat,
    'answer' : IDL.Text,
  });
  const Result_4 = IDL.Variant({ 'ok' : FAQ, 'err' : IDL.Text });
  const JournalEntry = IDL.Record({
    'id' : IDL.Text,
    'pnl' : IDL.Opt(IDL.Float64),
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'entryPrice' : IDL.Float64,
    'signal' : IDL.Text,
    'exitPrice' : IDL.Opt(IDL.Float64),
  });
  const MarketType = IDL.Variant({
    'Stock' : IDL.Null,
    'Forex' : IDL.Null,
    'Crypto' : IDL.Null,
  });
  const Direction = IDL.Variant({ 'Buy' : IDL.Null, 'Sell' : IDL.Null });
  const Confidence = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const Timeframe = IDL.Variant({
    'Scalp' : IDL.Null,
    'Swing' : IDL.Null,
    'LongTerm' : IDL.Null,
  });
  const ResultStatus = IDL.Variant({
    'Win' : IDL.Null,
    'Loss' : IDL.Null,
    'Active' : IDL.Null,
    'Expired' : IDL.Null,
  });
  const Signal = IDL.Record({
    'id' : IDL.Text,
    'result' : ResultStatus,
    'marketType' : MarketType,
    'direction' : Direction,
    'asset' : IDL.Text,
    'timeframe' : Timeframe,
    'publishAt' : IDL.Opt(IDL.Int),
    'targetPrice' : IDL.Text,
    'isDraft' : IDL.Bool,
    'datePosted' : IDL.Text,
    'stopLoss' : IDL.Text,
    'sourceLabel' : IDL.Text,
    'notes' : IDL.Text,
    'entryPrice' : IDL.Text,
    'expiry' : IDL.Opt(IDL.Int),
    'confidence' : Confidence,
  });
  const Result_3 = IDL.Variant({ 'ok' : Signal, 'err' : IDL.Text });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const AbTest = IDL.Record({
    'id' : IDL.Text,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'variantA' : IDL.Text,
    'variantB' : IDL.Text,
    'impressionsA' : IDL.Nat,
    'impressionsB' : IDL.Nat,
  });
  const Result_19 = IDL.Variant({ 'ok' : IDL.Vec(AbTest), 'err' : IDL.Text });
  const PushNotification = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'expiresAt' : IDL.Opt(IDL.Int),
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const ActivityEntry = IDL.Record({
    'dayOfWeek' : IDL.Nat,
    'hour' : IDL.Nat,
    'count' : IDL.Nat,
  });
  const Result_18 = IDL.Variant({
    'ok' : IDL.Vec(ActivityEntry),
    'err' : IDL.Text,
  });
  const MarketCount = IDL.Record({ 'count' : IDL.Nat, 'market' : IDL.Text });
  const DateCount = IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat });
  const Analytics = IDL.Record({
    'signalsByMarket' : IDL.Vec(MarketCount),
    'notifyMeByDate' : IDL.Vec(DateCount),
    'totalNotifyMe' : IDL.Nat,
  });
  const Result_17 = IDL.Variant({ 'ok' : Analytics, 'err' : IDL.Text });
  const Announcement = IDL.Record({
    'id' : IDL.Text,
    'link' : IDL.Opt(IDL.Text),
    'publishAt' : IDL.Opt(IDL.Int),
    'text' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const AuditEntry = IDL.Record({
    'id' : IDL.Text,
    'action' : IDL.Text,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
  });
  const Result_16 = IDL.Variant({
    'ok' : IDL.Vec(AuditEntry),
    'err' : IDL.Text,
  });
  const Result_15 = IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text });
  const BurnScheduleEntry = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'date' : IDL.Text,
    'txHash' : IDL.Opt(IDL.Text),
    'amount' : IDL.Text,
    'reason' : IDL.Text,
  });
  const BurnTracker = IDL.Record({
    'lastUpdated' : IDL.Int,
    'totalBurned' : IDL.Nat,
  });
  const CommunityCounter = IDL.Record({
    'lastUpdated' : IDL.Int,
    'binanceCount' : IDL.Nat,
    'twitterCount' : IDL.Nat,
  });
  const HolderBenefit = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'icon' : IDL.Text,
    'description' : IDL.Text,
  });
  const Result_14 = IDL.Variant({
    'ok' : IDL.Vec(JournalEntry),
    'err' : IDL.Text,
  });
  const MaintenanceMode = IDL.Record({
    'enabled' : IDL.Bool,
    'updatedAt' : IDL.Int,
    'message' : IDL.Text,
  });
  const MarketMoodBanner = IDL.Record({
    'active' : IDL.Bool,
    'mood' : IDL.Text,
    'updatedAt' : IDL.Int,
    'message' : IDL.Text,
  });
  const PriceData = IDL.Record({
    'trend' : IDL.Text,
    'asset' : IDL.Text,
    'updatedAt' : IDL.Int,
    'priceChange24h' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const SentimentLevel = IDL.Variant({
    'Bearish' : IDL.Null,
    'Neutral' : IDL.Null,
    'Bullish' : IDL.Null,
  });
  const AssetSentiment = IDL.Record({
    'trend' : IDL.Text,
    'asset' : IDL.Text,
    'note' : IDL.Text,
    'lastPriceUpdate' : IDL.Int,
    'level' : SentimentLevel,
    'updatedAt' : IDL.Int,
    'priceChange24h' : IDL.Float64,
    'market' : IDL.Text,
    'price' : IDL.Float64,
  });
  const MarketSentiment = IDL.Record({
    'assets' : IDL.Vec(AssetSentiment),
    'updatedAt' : IDL.Int,
    'overall' : SentimentLevel,
  });
  const CommunityMilestone = IDL.Record({
    'id' : IDL.Text,
    'reached' : IDL.Bool,
    'celebrateUntil' : IDL.Opt(IDL.Int),
    'title' : IDL.Text,
    'description' : IDL.Text,
    'reachedAt' : IDL.Opt(IDL.Int),
  });
  const NotifyMe = IDL.Record({
    'id' : IDL.Text,
    'contact' : IDL.Text,
    'dateSubmitted' : IDL.Text,
    'name' : IDL.Opt(IDL.Text),
  });
  const Result_13 = IDL.Variant({ 'ok' : IDL.Vec(NotifyMe), 'err' : IDL.Text });
  const DemonZenoQuote = IDL.Record({
    'id' : IDL.Text,
    'active' : IDL.Bool,
    'quote' : IDL.Text,
    'author' : IDL.Text,
  });
  const RoadmapMilestone = IDL.Record({
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'year' : IDL.Text,
    'description' : IDL.Text,
  });
  const Result_9 = IDL.Variant({ 'ok' : IDL.Vec(Signal), 'err' : IDL.Text });
  const ResponseRating = IDL.Record({
    'messageId' : IDL.Text,
    'timestamp' : IDL.Int,
    'rating' : IDL.Int,
  });
  const Result_12 = IDL.Variant({
    'ok' : IDL.Vec(ResponseRating),
    'err' : IDL.Text,
  });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'provider' : IDL.Opt(IDL.Text),
    'role' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const SignalOfWeekFull = IDL.Record({
    'featuredAt' : IDL.Int,
    'comment' : IDL.Text,
    'signal' : Signal,
    'weekOf' : IDL.Text,
  });
  const AssetStats = IDL.Record({
    'asset' : IDL.Text,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
  });
  const DayStats = IDL.Record({
    'day' : IDL.Text,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
  });
  const SignalPerformanceStats = IDL.Record({
    'topAssets' : IDL.Vec(AssetStats),
    'pending' : IDL.Nat,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'weeklyTrend' : IDL.Vec(DayStats),
    'winRate' : IDL.Float64,
    'totalSignals' : IDL.Nat,
  });
  const Result_11 = IDL.Variant({
    'ok' : SignalPerformanceStats,
    'err' : IDL.Text,
  });
  const Stats = IDL.Record({
    'active' : IDL.Nat,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'assetsCovered' : IDL.Nat,
    'winRate' : IDL.Float64,
    'totalSignals' : IDL.Nat,
  });
  const StatsConfig = IDL.Record({
    'useManual' : IDL.Bool,
    'manualStats' : IDL.Opt(Stats),
  });
  const Result_10 = IDL.Variant({ 'ok' : StatsConfig, 'err' : IDL.Text });
  const Testimonial = IDL.Record({
    'id' : IDL.Text,
    'active' : IDL.Bool,
    'content' : IDL.Text,
    'asset' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'winAmount' : IDL.Opt(IDL.Text),
  });
  const WhitepaperSection = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const WhitepaperContent = IDL.Record({
    'title' : IDL.Text,
    'updatedAt' : IDL.Int,
    'sections' : IDL.Vec(WhitepaperSection),
  });
  const SignalInput = IDL.Record({
    'marketType' : MarketType,
    'direction' : Direction,
    'asset' : IDL.Text,
    'timeframe' : Timeframe,
    'publishAt' : IDL.Opt(IDL.Int),
    'targetPrice' : IDL.Text,
    'isDraft' : IDL.Bool,
    'stopLoss' : IDL.Text,
    'sourceLabel' : IDL.Text,
    'notes' : IDL.Text,
    'entryPrice' : IDL.Text,
    'expiry' : IDL.Opt(IDL.Int),
    'confidence' : Confidence,
  });
  const AuditSnapshot = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'dataHash' : IDL.Text,
    'snapshotLabel' : IDL.Text,
  });
  const Result_8 = IDL.Variant({
    'ok' : IDL.Vec(AuditSnapshot),
    'err' : IDL.Text,
  });
  const Result_7 = IDL.Variant({ 'ok' : Announcement, 'err' : IDL.Text });
  const Result_6 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
  const Result_1 = IDL.Variant({
    'ok' : IDL.Tuple(IDL.Text, IDL.Text),
    'err' : IDL.Text,
  });
  
  return IDL.Service({
    'addBinancePost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result_5],
        [],
      ),
    'addBurnEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'addFaq' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_4], []),
    'addJournalEntry' : IDL.Func([JournalEntry, IDL.Text], [Result], []),
    'addMilestone' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
    'addQuote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
    'addSignal' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          MarketType,
          Direction,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Confidence,
          IDL.Text,
          IDL.Opt(IDL.Int),
          Timeframe,
          IDL.Bool,
          IDL.Opt(IDL.Int),
        ],
        [Result_3],
        [],
      ),
    'addTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
        [Result],
        [],
      ),
    'askFaq' : IDL.Func([IDL.Text], [IDL.Text], []),
    'backtestSignal' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'banEmail' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
    'checkAdminUnlockPhrase' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'clearJournal' : IDL.Func([IDL.Text], [Result_2], []),
    'createAbTest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'createAuditSnapshot' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'createPushNotification' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'deleteBinancePost' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
    'deleteFaq' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
    'deleteQuote' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
    'deleteSignal' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
    'deleteTestimonial' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
    'dismissPushNotification' : IDL.Func([IDL.Text], [], []),
    'generateDailyBriefing' : IDL.Func([IDL.Text], [Result], []),
    'getAbTests' : IDL.Func([IDL.Text], [Result_19], []),
    'getAbVariant' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getActivePushNotifications' : IDL.Func(
        [],
        [IDL.Vec(PushNotification)],
        ['query'],
      ),
    'getAdminActivityHeatmap' : IDL.Func([IDL.Text], [Result_18], []),
    'getAdminConfig' : IDL.Func([IDL.Text], [Result], []),
    'getAiLanguage' : IDL.Func([IDL.Text], [Result], ['query']),
    'getAiProviderStatus' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
        ['query'],
      ),
    'getAnalytics' : IDL.Func([IDL.Text], [Result_17], []),
    'getAnalyticsCsv' : IDL.Func([IDL.Text], [Result], []),
    'getAnnouncement' : IDL.Func([], [IDL.Opt(Announcement)], ['query']),
    'getAuditLog' : IDL.Func([IDL.Text], [Result_16], []),
    'getBannedEmails' : IDL.Func([IDL.Text], [Result_15], []),
    'getBinanceFeed' : IDL.Func([], [IDL.Vec(BinancePost)], ['query']),
    'getBurnSchedule' : IDL.Func([], [IDL.Vec(BurnScheduleEntry)], ['query']),
    'getBurnTracker' : IDL.Func([], [BurnTracker], ['query']),
    'getCommunityCounter' : IDL.Func([], [CommunityCounter], ['query']),
    'getDailyBriefing' : IDL.Func([], [IDL.Text], ['query']),
    'getFaqs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
    'getHolderBenefits' : IDL.Func([], [IDL.Vec(HolderBenefit)], ['query']),
    'getJournalEntries' : IDL.Func([IDL.Text], [Result_14], ['query']),
    'getMaintenanceMode' : IDL.Func([], [MaintenanceMode], ['query']),
    'getMarketMoodBanner' : IDL.Func(
        [],
        [IDL.Opt(MarketMoodBanner)],
        ['query'],
      ),
    'getMarketPrices' : IDL.Func([], [IDL.Vec(PriceData)], ['query']),
    'getMarketSentiment' : IDL.Func([], [MarketSentiment], ['query']),
    'getMilestones' : IDL.Func([], [IDL.Vec(CommunityMilestone)], ['query']),
    'getNotifyMeList' : IDL.Func([IDL.Text], [Result_13], []),
    'getPublicBurnSchedule' : IDL.Func(
        [],
        [IDL.Vec(BurnScheduleEntry)],
        ['query'],
      ),
    'getQuotes' : IDL.Func([], [IDL.Vec(DemonZenoQuote)], ['query']),
    'getRoadmap' : IDL.Func([], [IDL.Vec(RoadmapMilestone)], ['query']),
    'getScheduledSignals' : IDL.Func([IDL.Text], [Result_9], []),
    'getSessionRatings' : IDL.Func([IDL.Text], [Result_12], ['query']),
    'getSessionRecap' : IDL.Func(
        [IDL.Vec(ChatMessage), IDL.Text],
        [Result],
        [],
      ),
    'getSignalArchive' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
    'getSignalOfTheDay' : IDL.Func([], [IDL.Opt(Signal)], ['query']),
    'getSignalOfWeek' : IDL.Func([], [IDL.Opt(SignalOfWeekFull)], ['query']),
    'getSignalPerformanceStats' : IDL.Func([IDL.Text], [Result_11], []),
    'getSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getStatsConfig' : IDL.Func([IDL.Text], [Result_10], []),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getWhitepaper' : IDL.Func([], [WhitepaperContent], ['query']),
    'importSignals' : IDL.Func(
        [IDL.Text, IDL.Vec(SignalInput)],
        [Result_9],
        [],
      ),
    'initFaqs' : IDL.Func([], [], []),
    'invalidateAiSession' : IDL.Func([IDL.Text], [], []),
    'invalidateSession' : IDL.Func([IDL.Text], [], []),
    'listAuditSnapshots' : IDL.Func([IDL.Text], [Result_8], []),
    'markMilestoneReached' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [Result_2],
        [],
      ),
    'publishScheduledSignals' : IDL.Func([], [IDL.Nat], []),
    'rateAiResponse' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [Result_2], []),
    'recordAbImpression' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'recordAdminActivity' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
    'refreshMarketPrices' : IDL.Func([], [IDL.Vec(PriceData)], []),
    'reorderFaqs' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [Result_2], []),
    'scheduleSignal' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [Result_2], []),
    'sendAiMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ChatMessage)],
        [Result],
        [],
      ),
    'setAiApiKey' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_2], []),
    'setAiLanguage' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
    'setAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Int)],
        [Result_7],
        [],
      ),
    'setBurnTracker' : IDL.Func([IDL.Text, BurnTracker], [Result_2], []),
    'setCommunityCounter' : IDL.Func(
        [IDL.Text, CommunityCounter],
        [Result_2],
        [],
      ),
    'setMaintenanceMode' : IDL.Func(
        [IDL.Bool, IDL.Text, IDL.Text],
        [Result_2],
        [],
      ),
    'setMarketMoodBanner' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result_2],
        [],
      ),
    'setRoadmapMilestone' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [Result_2],
        [],
      ),
    'setSignalOfTheDay' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [Result_2],
        [],
      ),
    'setSignalOfWeek' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result_2],
        [],
      ),
    'setSignalOfWeekWithDate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result_2],
        [],
      ),
    'setStatsConfig' : IDL.Func([IDL.Text, StatsConfig], [Result_2], []),
    'submitNotifyMe' : IDL.Func([IDL.Opt(IDL.Text), IDL.Text], [Result_2], []),
    'toggleAnnouncement' : IDL.Func([IDL.Text], [Result_6], []),
    'unbanEmail' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
    'updateBinancePost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result_5],
        [],
      ),
    'updateBurnEntryStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [Result_2],
        [],
      ),
    'updateFaq' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result_4],
        [],
      ),
    'updateMarketSentiment' : IDL.Func(
        [IDL.Text, MarketSentiment],
        [Result_2],
        [],
      ),
    'updateSignal' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          MarketType,
          Direction,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Confidence,
          IDL.Text,
          IDL.Opt(IDL.Int),
          Timeframe,
          IDL.Bool,
          IDL.Opt(IDL.Int),
        ],
        [Result_3],
        [],
      ),
    'updateSignalResult' : IDL.Func(
        [IDL.Text, IDL.Text, ResultStatus],
        [Result_3],
        [],
      ),
    'updateSignalSchedule' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Opt(IDL.Int)],
        [Result_3],
        [],
      ),
    'updateWhitepaper' : IDL.Func(
        [WhitepaperContent, IDL.Text],
        [Result_2],
        [],
      ),
    'validateAdminRole' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'validateAiPasscode' : IDL.Func([IDL.Text], [Result_1], []),
    'validateAiSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'validateInsaneSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'validatePasscode' : IDL.Func([IDL.Text], [Result], []),
    'validateSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };