/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const CommunitySubmission = IDL.Record({
  'id' : IDL.Nat,
  'submitterHandle' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Timestamp,
});
export const CommunityStats = IDL.Record({
  'earlyBelieverCount' : IDL.Nat,
  'pledgeCount' : IDL.Nat,
  'hypeCount' : IDL.Nat,
  'interestCount' : IDL.Nat,
  'first100Count' : IDL.Nat,
  'submissionCount' : IDL.Nat,
});
export const EarlyBeliever = IDL.Record({
  'timestamp' : Timestamp,
  'handle' : IDL.Text,
  'index' : IDL.Nat,
});
export const First100Entry = IDL.Record({
  'isOG' : IDL.Bool,
  'timestamp' : Timestamp,
  'handle' : IDL.Text,
  'position' : IDL.Nat,
});
export const HypeMessage = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'handle' : IDL.Text,
});
export const InterestEntry = IDL.Record({
  'timestamp' : Timestamp,
  'handle' : IDL.Text,
});
export const RoadmapMilestone = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Opt(IDL.Text),
  'completed' : IDL.Bool,
  'year' : IDL.Text,
  'description' : IDL.Text,
});
export const TokenInfo = IDL.Record({
  'ticker' : IDL.Text,
  'socialLinks' : IDL.Vec(IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text })),
  'name' : IDL.Text,
  'launchPlatform' : IDL.Text,
  'description' : IDL.Text,
  'totalSupply' : IDL.Text,
  'slogan' : IDL.Text,
  'distribution' : IDL.Text,
});
export const Result_3 = IDL.Variant({ 'ok' : EarlyBeliever, 'err' : IDL.Text });
export const Result_2 = IDL.Variant({ 'ok' : First100Entry, 'err' : IDL.Text });
export const Result_1 = IDL.Variant({ 'ok' : HypeMessage, 'err' : IDL.Text });
export const Result = IDL.Variant({ 'ok' : InterestEntry, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'getCommunityPosts' : IDL.Func([], [IDL.Vec(CommunitySubmission)], ['query']),
  'getCommunityStats' : IDL.Func([], [CommunityStats], ['query']),
  'getEarlyBelievers' : IDL.Func([], [IDL.Vec(EarlyBeliever)], ['query']),
  'getFirst100' : IDL.Func([], [IDL.Vec(First100Entry)], ['query']),
  'getHypeMessages' : IDL.Func([], [IDL.Vec(HypeMessage)], ['query']),
  'getInterestSubmissions' : IDL.Func([], [IDL.Vec(InterestEntry)], ['query']),
  'getPledgeCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getRoadmap' : IDL.Func([], [IDL.Vec(RoadmapMilestone)], ['query']),
  'getTokenInfo' : IDL.Func([], [TokenInfo], ['query']),
  'submitCommunityPost' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'submitEarlyBeliever' : IDL.Func([IDL.Text], [Result_3], []),
  'submitFirst100' : IDL.Func([IDL.Text], [Result_2], []),
  'submitHypeMessage' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'submitInterest' : IDL.Func([IDL.Text], [Result], []),
  'submitPledge' : IDL.Func([IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const CommunitySubmission = IDL.Record({
    'id' : IDL.Nat,
    'submitterHandle' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const CommunityStats = IDL.Record({
    'earlyBelieverCount' : IDL.Nat,
    'pledgeCount' : IDL.Nat,
    'hypeCount' : IDL.Nat,
    'interestCount' : IDL.Nat,
    'first100Count' : IDL.Nat,
    'submissionCount' : IDL.Nat,
  });
  const EarlyBeliever = IDL.Record({
    'timestamp' : Timestamp,
    'handle' : IDL.Text,
    'index' : IDL.Nat,
  });
  const First100Entry = IDL.Record({
    'isOG' : IDL.Bool,
    'timestamp' : Timestamp,
    'handle' : IDL.Text,
    'position' : IDL.Nat,
  });
  const HypeMessage = IDL.Record({
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'handle' : IDL.Text,
  });
  const InterestEntry = IDL.Record({
    'timestamp' : Timestamp,
    'handle' : IDL.Text,
  });
  const RoadmapMilestone = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Opt(IDL.Text),
    'completed' : IDL.Bool,
    'year' : IDL.Text,
    'description' : IDL.Text,
  });
  const TokenInfo = IDL.Record({
    'ticker' : IDL.Text,
    'socialLinks' : IDL.Vec(
      IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text })
    ),
    'name' : IDL.Text,
    'launchPlatform' : IDL.Text,
    'description' : IDL.Text,
    'totalSupply' : IDL.Text,
    'slogan' : IDL.Text,
    'distribution' : IDL.Text,
  });
  const Result_3 = IDL.Variant({ 'ok' : EarlyBeliever, 'err' : IDL.Text });
  const Result_2 = IDL.Variant({ 'ok' : First100Entry, 'err' : IDL.Text });
  const Result_1 = IDL.Variant({ 'ok' : HypeMessage, 'err' : IDL.Text });
  const Result = IDL.Variant({ 'ok' : InterestEntry, 'err' : IDL.Text });
  
  return IDL.Service({
    'getCommunityPosts' : IDL.Func(
        [],
        [IDL.Vec(CommunitySubmission)],
        ['query'],
      ),
    'getCommunityStats' : IDL.Func([], [CommunityStats], ['query']),
    'getEarlyBelievers' : IDL.Func([], [IDL.Vec(EarlyBeliever)], ['query']),
    'getFirst100' : IDL.Func([], [IDL.Vec(First100Entry)], ['query']),
    'getHypeMessages' : IDL.Func([], [IDL.Vec(HypeMessage)], ['query']),
    'getInterestSubmissions' : IDL.Func(
        [],
        [IDL.Vec(InterestEntry)],
        ['query'],
      ),
    'getPledgeCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getRoadmap' : IDL.Func([], [IDL.Vec(RoadmapMilestone)], ['query']),
    'getTokenInfo' : IDL.Func([], [TokenInfo], ['query']),
    'submitCommunityPost' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'submitEarlyBeliever' : IDL.Func([IDL.Text], [Result_3], []),
    'submitFirst100' : IDL.Func([IDL.Text], [Result_2], []),
    'submitHypeMessage' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'submitInterest' : IDL.Func([IDL.Text], [Result], []),
    'submitPledge' : IDL.Func([IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };