/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type TierId = string;
export interface RoadmapMilestone {
    id: string;
    title: string;
    date?: string;
    completed: boolean;
    year: string;
    description: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface QuizAnswer {
    questionId: string;
    selectedOption: string;
}
export interface ZenoAiResponse {
    answer: string;
    success: boolean;
}
export interface TokenInfo {
    ticker: string;
    socialLinks: Array<{
        url: string;
        name: string;
    }>;
    name: string;
    launchPlatform: string;
    description: string;
    totalSupply: string;
    slogan: string;
    distribution: string;
}
export interface QuizQuestion {
    id: string;
    correctOption: string;
    question: string;
    explanation: string;
    isReviewFlagged: boolean;
    options: Array<QuizOption>;
}
export interface QuestionFailStat {
    tierId: string;
    totalSeen: bigint;
    questionId: string;
    failCount: bigint;
}
export interface DailyActiveLog {
    date: string;
    count: bigint;
}
export interface AnnouncementBanner {
    text: string;
    updatedAt: bigint;
    isPinned: boolean;
}
export interface TierQuiz {
    tierId: TierId;
    tierName: string;
    questions: Array<QuizQuestion>;
}
export type Result_1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TierDisabledEntry {
    tierId: string;
    disabled: boolean;
}
export type Result = {
    __kind__: "ok";
    ok: Certificate;
} | {
    __kind__: "err";
    err: string;
};
export interface AdminStats {
    certsByTier: Array<[string, bigint]>;
    totalCertificates: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface QuizAttemptStats {
    tierId: string;
    passCount: bigint;
    totalAttempts: bigint;
}
export interface CertificateInfo {
    country: string;
    dateOfBirth: string;
    city: string;
    fullName: string;
    fathersName: string;
    email: string;
}
export interface QuizOption {
    id: string;
    text: string;
}
export interface LessonRating {
    lessonId: string;
    tierId: string;
    timestamp: bigint;
    rating: bigint;
}
export interface LessonCompletionLog {
    lessonId: string;
    completedAt: bigint;
    tierId: string;
}
export interface Certificate {
    certId: string;
    featured: boolean;
    certInfo: CertificateInfo;
    tierId: TierId;
    tierName: string;
    shareToken: string;
    score: bigint;
    totalQuestions: bigint;
    issuedAt: bigint;
    isValid: boolean;
}
export interface QuizAttemptLog {
    tierId: string;
    score: bigint;
    fingerprint: string;
    timestamp: bigint;
    passed: boolean;
}
export interface backendInterface {
    adminExportCertificates(): Promise<Array<Certificate>>;
    adminFeatureCertificate(certId: string, featured: boolean): Promise<Result_1>;
    adminFlagQuestion(questionId: string, flagged: boolean): Promise<void>;
    adminGetAttemptLogs(tierId: string): Promise<Array<QuizAttemptLog>>;
    adminGetFlaggedQuestions(): Promise<Array<string>>;
    adminGetQuestionFailStats(tierId: string): Promise<Array<QuestionFailStat>>;
    adminGetStats(): Promise<AdminStats>;
    adminManualIssueCertificate(tierId: string, info: CertificateInfo): Promise<Result>;
    adminRevokeOrReinstateCertificate(certId: string, isValid: boolean): Promise<Result_1>;
    adminSetAnnouncementBanner(text: string, isPinned: boolean): Promise<void>;
    adminSetTierDisabled(tierId: string, disabled: boolean): Promise<Result_1>;
    adminUpdateMilestone(id: string, completed: boolean): Promise<Result_1>;
    askZenoAi(question: string): Promise<ZenoAiResponse>;
    getAcademyQuiz(tierId: string, seed: bigint): Promise<TierQuiz | null>;
    getAdminLessonRatings(): Promise<Array<[string, string, number]>>;
    getAnnouncementBanner(): Promise<AnnouncementBanner | null>;
    getCertificateByShareToken(shareToken: string): Promise<Certificate | null>;
    getCertificatesByTier(tierId: string): Promise<Array<Certificate>>;
    getDailyActiveCounts(): Promise<Array<DailyActiveLog>>;
    getFeaturedCertificates(): Promise<Array<Certificate>>;
    getFeaturedLesson(tierId: string): Promise<string | null>;
    getLessonCompletionTrends(): Promise<Array<LessonCompletionLog>>;
    getLessonRatings(tierId: string, lessonId: string): Promise<Array<LessonRating>>;
    getQuizAttemptStats(): Promise<Array<QuizAttemptStats>>;
    getQuizFailMessage(tierId: string): Promise<string | null>;
    getRoadmap(): Promise<Array<RoadmapMilestone>>;
    getTierDisabledStates(): Promise<Array<TierDisabledEntry>>;
    getTokenInfo(): Promise<TokenInfo>;
    listAllCertificates(): Promise<Array<Certificate>>;
    logDailyActive(date: string): Promise<void>;
    logLessonCompletion(tierId: string, lessonId: string, timestamp: bigint): Promise<void>;
    searchCertificates(searchTerm: string): Promise<Array<Certificate>>;
    setFeaturedLesson(tierId: string, lessonId: string, passcode: string): Promise<boolean>;
    setQuizFailMessage(tierId: string, message: string, passcode: string): Promise<boolean>;
    submitCheckpointQuiz(tierId: string, score: bigint): Promise<boolean>;
    submitLessonRating(tierId: string, lessonId: string, rating: bigint): Promise<boolean>;
    submitQuizAndIssueCertificate(tierId: string, answers: Array<QuizAnswer>, fullName: string, fathersName: string, country: string, dateOfBirth: string, email: string, city: string, seed: bigint, fingerprint: string): Promise<Result>;
    verifyCertificate(certId: string): Promise<Certificate | null>;
    zenoAiTransform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { AnnouncementBanner as _AnnouncementBanner, Certificate as _Certificate, Result as _Result, Result_1 as _Result_1, RoadmapMilestone as _RoadmapMilestone, TierQuiz as _TierQuiz } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminExportCertificates(): Promise<Array<Certificate>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminExportCertificates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminExportCertificates();
            return result;
        }
    }
    async adminFeatureCertificate(arg0: string, arg1: boolean): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.adminFeatureCertificate(arg0, arg1);
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminFeatureCertificate(arg0, arg1);
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminFlagQuestion(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminFlagQuestion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminFlagQuestion(arg0, arg1);
            return result;
        }
    }
    async adminGetAttemptLogs(arg0: string): Promise<Array<QuizAttemptLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAttemptLogs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAttemptLogs(arg0);
            return result;
        }
    }
    async adminGetFlaggedQuestions(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetFlaggedQuestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetFlaggedQuestions();
            return result;
        }
    }
    async adminGetQuestionFailStats(arg0: string): Promise<Array<QuestionFailStat>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetQuestionFailStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetQuestionFailStats(arg0);
            return result;
        }
    }
    async adminGetStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetStats();
            return result;
        }
    }
    async adminManualIssueCertificate(arg0: string, arg1: CertificateInfo): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminManualIssueCertificate(arg0, arg1);
                return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminManualIssueCertificate(arg0, arg1);
            return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRevokeOrReinstateCertificate(arg0: string, arg1: boolean): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRevokeOrReinstateCertificate(arg0, arg1);
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRevokeOrReinstateCertificate(arg0, arg1);
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminSetAnnouncementBanner(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetAnnouncementBanner(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetAnnouncementBanner(arg0, arg1);
            return result;
        }
    }
    async adminSetTierDisabled(arg0: string, arg1: boolean): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetTierDisabled(arg0, arg1);
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetTierDisabled(arg0, arg1);
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateMilestone(arg0: string, arg1: boolean): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateMilestone(arg0, arg1);
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateMilestone(arg0, arg1);
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async askZenoAi(arg0: string): Promise<ZenoAiResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.askZenoAi(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.askZenoAi(arg0);
            return result;
        }
    }
    async getAcademyQuiz(arg0: string, arg1: bigint): Promise<TierQuiz | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAcademyQuiz(arg0, arg1);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAcademyQuiz(arg0, arg1);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminLessonRatings(): Promise<Array<[string, string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminLessonRatings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminLessonRatings();
            return result;
        }
    }
    async getAnnouncementBanner(): Promise<AnnouncementBanner | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnouncementBanner();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnouncementBanner();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCertificateByShareToken(arg0: string): Promise<Certificate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCertificateByShareToken(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCertificateByShareToken(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCertificatesByTier(arg0: string): Promise<Array<Certificate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCertificatesByTier(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCertificatesByTier(arg0);
            return result;
        }
    }
    async getDailyActiveCounts(): Promise<Array<DailyActiveLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyActiveCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyActiveCounts();
            return result;
        }
    }
    async getFeaturedCertificates(): Promise<Array<Certificate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedCertificates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedCertificates();
            return result;
        }
    }
    async getFeaturedLesson(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedLesson(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedLesson(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLessonCompletionTrends(): Promise<Array<LessonCompletionLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessonCompletionTrends();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessonCompletionTrends();
            return result;
        }
    }
    async getLessonRatings(arg0: string, arg1: string): Promise<Array<LessonRating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessonRatings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessonRatings(arg0, arg1);
            return result;
        }
    }
    async getQuizAttemptStats(): Promise<Array<QuizAttemptStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizAttemptStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizAttemptStats();
            return result;
        }
    }
    async getQuizFailMessage(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizFailMessage(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizFailMessage(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoadmap(): Promise<Array<RoadmapMilestone>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoadmap();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoadmap();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTierDisabledStates(): Promise<Array<TierDisabledEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTierDisabledStates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTierDisabledStates();
            return result;
        }
    }
    async getTokenInfo(): Promise<TokenInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getTokenInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTokenInfo();
            return result;
        }
    }
    async listAllCertificates(): Promise<Array<Certificate>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllCertificates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllCertificates();
            return result;
        }
    }
    async logDailyActive(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logDailyActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logDailyActive(arg0);
            return result;
        }
    }
    async logLessonCompletion(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logLessonCompletion(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logLessonCompletion(arg0, arg1, arg2);
            return result;
        }
    }
    async searchCertificates(arg0: string): Promise<Array<Certificate>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCertificates(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCertificates(arg0);
            return result;
        }
    }
    async setFeaturedLesson(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setFeaturedLesson(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFeaturedLesson(arg0, arg1, arg2);
            return result;
        }
    }
    async setQuizFailMessage(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setQuizFailMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setQuizFailMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async submitCheckpointQuiz(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCheckpointQuiz(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCheckpointQuiz(arg0, arg1);
            return result;
        }
    }
    async submitLessonRating(arg0: string, arg1: string, arg2: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLessonRating(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLessonRating(arg0, arg1, arg2);
            return result;
        }
    }
    async submitQuizAndIssueCertificate(arg0: string, arg1: Array<QuizAnswer>, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: bigint, arg9: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuizAndIssueCertificate(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuizAndIssueCertificate(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyCertificate(arg0: string): Promise<Certificate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyCertificate(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyCertificate(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async zenoAiTransform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.zenoAiTransform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.zenoAiTransform(arg0);
            return result;
        }
    }
}
function from_candid_Result_1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_RoadmapMilestone_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoadmapMilestone): RoadmapMilestone {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TierQuiz]): TierQuiz | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AnnouncementBanner]): AnnouncementBanner | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Certificate]): Certificate | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    date: [] | [string];
    completed: boolean;
    year: string;
    description: string;
}): {
    id: string;
    title: string;
    date?: string;
    completed: boolean;
    year: string;
    description: string;
} {
    return {
        id: value.id,
        title: value.title,
        date: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.date)),
        completed: value.completed,
        year: value.year,
        description: value.description
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Certificate;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Certificate;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RoadmapMilestone>): Array<RoadmapMilestone> {
    return value.map((x)=>from_candid_RoadmapMilestone_n10(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
